model:
  z_dim: 28
  hidden_dim: 64
  num_layer: 4

solver:
  results_folder: ./Checkpoints_energy
  n_iters: 80000
  learning_rate: 0.001
  w_gamma: 1.0
  w_g: 100.0

dataloader:
  target: Utils.Data_utils.real_datasets.CustomDataset
  params:
    name: energy
    train_size: 0.8
    data_root: ./Data/datasets/labeled_energy_data.npy
    window: 24  # seq_length
    save2npy: True
    neg_one_to_one: True
    seed: 123
    style: separate
    distribution: geometric

  batch_size: 64
  shuffle: True