model:
  z_dim: 50
  hidden_dim: 128
  num_layer: 3

solver:
  results_folder: ./Checkpoints_fmri
  n_iters: 80000
  learning_rate: 0.001
  w_gamma: 1.0
  w_g: 100.0

dataloader:
  target: Utils.Data_utils.real_datasets.CustomDataset
  params:
    name: fMRI
    train_size: 0.8
    data_root: ./Data/datasets/fMRI/labeled_sim4.npy
    window: 24  # seq_length
    save2npy: True
    neg_one_to_one: True
    seed: 123
    style: separate
    distribution: geometric

  batch_size: 64
  shuffle: True