model:
  z_dim: 14
  hidden_dim: 32
  num_layer: 3

solver:
  results_folder: ./Checkpoints_mujoco
  n_iters: 60000
  learning_rate: 0.001
  w_gamma: 1.0
  w_g: 100.0

dataloader:
  target: Utils.Data_utils.real_datasets.CustomDataset
  params:
    name: mujoco
    train_size: 0.8
    data_root: ./Data/datasets/labeled_mujoco.npy
    window: 24  # seq_length
    save2npy: True
    neg_one_to_one: True
    seed: 123
    style: separate
    distribution: geometric

  batch_size: 128
  shuffle: True